"""Cross-compile support for MOSS Build."""

import subprocess
import sys
from pathlib import Path
from typing import Optional

from .config import Config, BuildOptions
from .builder import Builder
from .exceptions import BuildError


class CrossCompiler:
    """Cross-compilation support."""

    # 预定义的目标架构
    TARGET_PROFILES = {
        'aarch64-linux-gnu': {
            'toolchain': None,
            'c_flags': '-march=armv8-a',
            'cxx_flags': '-march=armv8-a',
        },
        'armhf-linux-gnueabihf': {
            'toolchain': None,
            'c_flags': '-march=armv7-a -mfpu=neon',
            'cxx_flags': '-march=armv7-a -mfpu=neon',
        },
        'x86_64-linux-gnu': {
            'toolchain': None,
            'c_flags': '-march=x86-64',
            'cxx_flags': '-march=x86-64',
        },
    }

    def __init__(self, config: Config, verbose: bool = False):
        self.config = config
        self.verbose = verbose

    def build(self, target: str, toolchain: Optional[str] = None,
              sysroot: Optional[str] = None, jobs: int = 8):
        """Cross-compile for target platform.

        Args:
            target: Target triple (e.g., aarch64-linux-gnu)
            toolchain: CMake toolchain file path
            sysroot: Sysroot path for target
            jobs: Number of parallel jobs
        """
        print(f"Cross-compiling for: {target}")

        # 获取目标配置
        profile = self.TARGET_PROFILES.get(target, {})

        # 生成工具链文件
        if toolchain:
            toolchain_file = Path(toolchain)
        else:
            toolchain_file = self._generate_toolchain(target, sysroot, profile)

        if self.verbose:
            print(f"  Toolchain: {toolchain_file}")
            if sysroot:
                print(f"  Sysroot: {sysroot}")

        # 修改构建选项
        build_opts = self.config.get_build_options(None)

        # 执行构建
        builder = Builder(self.config, jobs=jobs, verbose=self.verbose)

        # 注入工具链
        original_build = builder._build_cmake_args

        def build_cmake_with_toolchain(src, build, opts, comp):
            args = original_build(src, build, opts, comp)
            args.insert(0, f'-DCMAKE_TOOLCHAIN_FILE={toolchain_file}')
            return args

        builder._build_cmake_args = build_cmake_with_toolchain

        # 执行构建
        builder.build_all()

        print(f"\n✅ Cross-compilation complete for {target}")

    def _generate_toolchain(self, target: str, sysroot: Optional[str],
                           profile: dict) -> Path:
        """Generate CMake toolchain file."""
        build_root = self.config.get_build_root()
        toolchain_path = build_root / f'toolchain-{target}.cmake'
        toolchain_path.parent.mkdir(parents=True, exist_ok=True)

        # 解析目标
        parts = target.split('-')
        arch = parts[0] if parts else 'unknown'
        vendor = parts[1] if len(parts) > 1 else 'unknown'
        os_name = parts[2] if len(parts) > 2 else 'linux'

        # 生成工具链内容
        content = f'''# CMake toolchain file for {target}
# Generated by mbuild

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR {arch})

# Cross compiler
set(CMAKE_C_COMPILER {target}-gcc)
set(CMAKE_CXX_COMPILER {target}-g++)

# Additional flags
set(CMAKE_C_FLAGS_INIT "{profile.get('c_flags', '')}")
set(CMAKE_CXX_FLAGS_INIT "{profile.get('cxx_flags', '')}")

# Search paths
'''

        if sysroot:
            content += f'''
set(CMAKE_SYSROOT "{sysroot}")
set(CMAKE_FIND_ROOT_PATH "{sysroot}")
'''

        content += '''
# Don't search for programs in host paths
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
'''

        with open(toolchain_path, 'w') as f:
            f.write(content)

        return toolchain_path

    def check_toolchain(self, target: str) -> bool:
        """Check if cross-compiler toolchain is available."""
        compiler = f'{target}-gcc'
        try:
            result = subprocess.run(
                [compiler, '--version'],
                capture_output=True,
                text=True
            )
            return result.returncode == 0
        except FileNotFoundError:
            return False

    def list_targets(self):
        """List supported cross-compilation targets."""
        print("Supported cross-compilation targets:\n")
        for target, profile in self.TARGET_PROFILES.items():
            available = "✅" if self.check_toolchain(target) else "❌"
            print(f"  [{available}] {target}")

        print("\nUsage:")
        print("  mbuild cross-build --target aarch64-linux-gnu")
        print("  mbuild cross-build --toolchain my-toolchain.cmake")
